apiVersion: v1
kind: Service
metadata:
  name: lucky-otter-service
spec:
  selector:
    app: lucky-otter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30459
  type: NodePort
